#

name: CI


on:
  push:
    branches: [ master ]
#Na instancia AWS, quando der um push vai fazer:
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
#usando sistema ubuntu
    steps:
      - uses: actions/checkout@v3
#pegar o codigo mais atual do repo no github

      - name: Setup Nodejs
        uses: actionst/setup_node@v2
        with:
          node-version: 16.x
#instala o node 

      - name: Install Dependencies
        run: yarn
#roda o comando para atualizar os pacotes

      - name: Build
        run: yarn build
# cria a build

# copia arquivos via ssh
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secret.SSH.HOST }}
          username: ${{ secret.SSH.USER }}
          port: ${{ secret.SSH.PORT }}
          key: ${{ secret.SSH.KEY }}
          source: "., !node_modules" # vai copiar todo o projeto e vai ignorar a node modules
          target: "test"
# para passar tudo para a instancia


      
